### PR TITLE
S4662: Ignore Sass/SCSS `@use` at-rule (#252)

### PR DESCRIPTION
**Pull request by teddywing**
Eliminate false-positives for the Sass/SCSS `@use` at-rule.

### CODE REVIEW

**Comment by vilchik-elena** [comment]
Hi,

thanks for the PR! we will take care of it when doing next sprint for this analyzer (no estimate so far)

**Comment by teddywing** [comment]
Sounds good, and thanks for the update.

**Comment by pburkindine** [comment]
This also needs to include @forward

https://sass-lang.com/documentation/at-rules/forward

**Comment by andrea-guarino-sonarsource** [comment]
Hi @teddywing ,
I included your commit on #326 in order to have a full pipeline. 
Thanks a lot for your contribution!

**Comment by teddywing** [comment]
@andrea-guarino-sonarsource Nice, thanks for merging this!

**Pull request closed without merging**
