### PR TITLE
Updates stylelint to latest version to support latest CSS properties

### LINKED ISSUE #264: Unexpected unknown property "content-visibility", "contain-intrinsic-size"
`content-visibility` and `contain-intrinsic-size` came with Chrome 85 and are not support.

image

### PR DESCRIPTION
**Pull request by rmachado-elsevier**
#### What does this PR do
* Updates `stylelint` to latest (minor) version to support `content-visibility` and `contain-intrinsic-size` (new) properties

Fixes #264

Note: Further explanation on the cause of the issue can be found in the fixed issue #264 .

# Where should the reviewer start
* `package.json`
* `yarn.lock`

### CODE REVIEW

**Comment by kirankalyan5** [comment]
+1, 
Looking forward to this PR to be merged.

**Comment by rmachado-elsevier** [comment]
@vilchik-elena, sorry to mention, but just to confirm... Are you accepting external PRs?

**Comment by saberduck** [comment]
hello @rmachado-elsevier , we accept minor external contributions, however we have limited bandwidth to process them, so you should accept sometimes long delay while we get to merging and releasing the change.

In this case there is another constraint, that new stylelint requires Node.JS 10, so we need to give some transition period to our users to update their CI pipelines for this change. We are currently discussing the deadline for this, it should happen by the end of the year.

**Comment by rmachado-elsevier** [comment]
> hello @rmachado-elsevier , we accept minor external contributions, however we have limited bandwidth to process them, so you should accept sometimes long delay while we get to merging and releasing the change.
> 
> In this case there is another constraint, that new stylelint requires Node.JS 10, so we need to give some transition period to our users to update their CI pipelines for this change. We are currently discussing the deadline for this, it should happen by the end of the year.

Very well... Since you're using `yarn` I'll try the `resolutions` approach, for the specific package `known-css-properties`...

**Pull request closed without merging**
