### PR TITLE
Support for css-modules

### PR DESCRIPTION
**Pull request by kmcrawford**
add support for @value, composes, import, & export

### CODE REVIEW

**Comment by kadikraman** [comment]
This is exactly what we need! Are you planning to release this soon?

**Comment by alowdon** [comment]
This would be great for us as well, any news on merging it? It's frustrating to have these show as blocker bugs, and there doesn't seem to be a way of disabling the rule with an inline comment.

**Comment by marques-p44** [comment]
Can we get this PR merged?

**Comment by bbehling-trimble** [comment]
Can this be merged?

**Comment by vilchik-elena** [comment]
Migrated to https://github.com/SonarSource/sonar-css/pull/171

**Pull request closed without merging**
